// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceModel.proto

package com.li.rpc.domain;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.DataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string instanceId = 1;</code>
   * @return The instanceId.
   */
  java.lang.String getInstanceId();
  /**
   * <code>string instanceId = 1;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string data = 3;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 3;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
