// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceModel.proto

package com.li.rpc.domain;

public interface DataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.li.rpc.DataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string instanceId = 1;</code>
   * @return The instanceId.
   */
  java.lang.String getInstanceId();
  /**
   * <code>string instanceId = 1;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
