// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceModel.proto

package com.li.rpc.domain;

public final class GrpcServiceModel {
  private GrpcServiceModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_li_rpc_DataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_li_rpc_DataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026GrpcServiceModel.proto\022\ncom.li.rpc\"=\n\013" +
      "DataRequest\022\022\n\ninstanceId\030\001 \001(\t\022\014\n\004name\030" +
      "\002 \001(\t\022\014\n\004data\030\003 \001(\t\"3\n\014DataResponse\022\022\n\ni" +
      "nstanceId\030\001 \001(\t\022\017\n\007message\030\002 \001(\tB\'\n\021com." +
      "li.rpc.domainB\020GrpcServiceModelP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_li_rpc_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_li_rpc_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_DataRequest_descriptor,
        new java.lang.String[] { "InstanceId", "Name", "Data", });
    internal_static_com_li_rpc_DataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_li_rpc_DataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_li_rpc_DataResponse_descriptor,
        new java.lang.String[] { "InstanceId", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
